/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.ui;

import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author akshaygurao
 */
public class MainFrame extends javax.swing.JFrame {

    private static void updateParameters(MainFrame mf) {
    	UIController c = new UIController();
        c.setCurrTemp(c.getGenerator().nextInt(120));
        System.out.println(c.getCurrTemp());
        mf.currentTemp.setText(String.valueOf(c.getCurrTemp()));
        mf.setTemp.setText(String.valueOf(c.getSetTemp()));
        mf.eventTrigg.setText(c.getEvent());
        mf.selectRoomJComboBox.removeAllItems();
        c.getRooms().forEach(r -> mf.selectRoomJComboBox.addItem(r));
		
	}

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        selectRoomLabel = new javax.swing.JLabel();
        selectRoomJComboBox = new javax.swing.JComboBox<>();
        currTempLabel = new javax.swing.JLabel();
        setTempLabel = new javax.swing.JLabel();
        eventTriggeredLabel = new javax.swing.JLabel();
        currentTemp = new javax.swing.JTextField();
        setTemp = new javax.swing.JTextField();
        eventTrigg = new javax.swing.JTextField();
        degreeLabel = new javax.swing.JLabel();
        degreeLabel2 = new javax.swing.JLabel();
        sendBtn = new javax.swing.JButton();
        rrecvBtn = new javax.swing.JButton();
        generaterandomBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Thermostat");

        selectRoomLabel.setText("Select Room: ");

        selectRoomJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectRoomJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRoomJComboBoxActionPerformed(evt);
            }
        });

        currTempLabel.setText("Current Temperature:");

        setTempLabel.setText("Set Temperature:");

        eventTriggeredLabel.setText("Event Triggered:");

        currentTemp.setEditable(false);
        currentTemp.setText("65");
        currentTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTempActionPerformed(evt);
            }
        });

        setTemp.setEditable(false);
        setTemp.setText("70");
        setTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTempActionPerformed(evt);
            }
        });

        eventTrigg.setEditable(false);
        eventTrigg.setText("False");

        degreeLabel.setText("°C");

        degreeLabel2.setText("°C");

        sendBtn.setText("Send");

        rrecvBtn.setText("Recieve");
        rrecvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rrecvBtnActionPerformed(evt);
            }
        });

        generaterandomBtn.setText("Generate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectRoomLabel)
                            .addComponent(currTempLabel)
                            .addComponent(setTempLabel)
                            .addComponent(eventTriggeredLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(selectRoomJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(setTemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(currentTemp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventTrigg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(degreeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sendBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rrecvBtn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(degreeLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(generaterandomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectRoomLabel)
                    .addComponent(selectRoomJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currTempLabel)
                    .addComponent(currentTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degreeLabel)
                    .addComponent(sendBtn)
                    .addComponent(rrecvBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setTempLabel)
                            .addComponent(setTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eventTriggeredLabel)
                            .addComponent(eventTrigg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(generaterandomBtn))
                .addGap(0, 273, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void selectRoomJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void currentTempActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void setTempActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void rrecvBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        for(int i = 0; i < 10; i++){
            updateParameters(mf);
                try {
					Thread.sleep(1000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        }
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            MainFrame mf = new MainFrame();
//            public void run() {
//                    mf.setVisible(true);
//                    updateParameters();
//            }
//
//            private void updateParameters() {
//                Controller c = new Controller();
//                mf.currentTemp.setText(String.valueOf(c.getCurrTemp()));
//                mf.setTemp.setText(String.valueOf(c.getSetTemp()));
//                mf.eventTrigg.setText(c.getEvent());
//                mf.selectRoomJComboBox.removeAllItems();
//                c.getRooms().forEach(r -> mf.selectRoomJComboBox.addItem(r));
//            }
//        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel currTempLabel;
    private javax.swing.JTextField currentTemp;
    private javax.swing.JLabel degreeLabel;
    private javax.swing.JLabel degreeLabel2;
    private javax.swing.JTextField eventTrigg;
    private javax.swing.JLabel eventTriggeredLabel;
    private javax.swing.JButton generaterandomBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rrecvBtn;
    private javax.swing.JComboBox<String> selectRoomJComboBox;
    private javax.swing.JLabel selectRoomLabel;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField setTemp;
    private javax.swing.JLabel setTempLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration                   
}
